version: "3.9"

networks:
  my_network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
    env_file:
      - .env
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
      - /var/www/html:/usr/share/nginx/html
    depends_on:
      - web
    networks:
      - my_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --agree-tos --non-interactive --email=<your-email> --domains <your-domain> --server https://acme.sectigo.com/v2/GEANTOV --eab-kid ${ACME_KID} --eab-hmac-key ${ACME_HMAC} --cert-name OVcert
    networks:
      - my_network
    depends_on:
      - nginx
    restart: "no"
    environment:
      - ACME_KID
      - ACME_HMAC

volumes:
  letsencrypt:
  mysql_data:
