version: "3.9"

networks:
  my_network:
    # driver: bridge

services:
  web:
    build: .
    command: ["tail", "-f", "/dev/null"]
    # These are the commands that will be run when the container is started
    # You could also run these commands within the container itselft
    # For example: docker exec -it <container_name> python manage.py collectstatic --noinput
    # Or docker get inside the container via the terminal: exec -it <container_name> sh     
    # command: >
    #  sh -c "sh /wait-for.sh db:3308 --
    #         python manage.py migrate &&
    #         python manage.py runserver 0.0.0.0:5000"
    ports:
      - "5001:5000"
    # restart: always
    depends_on:
      - db
      - redis

    links:
      - "db:db"
  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      - ALLOWED_HOSTS="localhost"
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_LILIANA_PORT}
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    restart: always

volumes:
  mysql_data:
